import pandas as pd
import logging
logger = logging.getLogger('keiba_ebye')

def generate_pdf_report(results_list, ev_threshold=1.5):
    """
    予想レポートをHTML形式で生成してbytesを返す。
    ブラウザで開いてCtrl+P(Cmd+P)で印刷・PDF保存できる。
    reportlabのフォント問題を回避するためHTML方式に変更。
    """
    try:
        ev_summary = []
        races_html = ""
        for r in results_list:
            df = r['df']
            rows_html = ""
            for rank, row in df.iterrows():
                try:
                    ev_val = float(row.get('期待値', 0) or 0)
                except: ev_val = 0.0
                bg = ' style="background:#fff0f0"' if ev_val >= ev_threshold else (' style="background:#fffde7"' if rank == 0 else '')
                ev_color = ' color:#cc0000;font-weight:bold' if ev_val >= ev_threshold else ''
                rows_html += f"""<tr{bg}>
                  <td>{row.get('印','')}</td>
                  <td>{int(float(row.get('馬番',0)))}</td>
                  <td>{row.get('馬名','')}</td>
                  <td>{row.get('脚質カテゴリ','')}</td>
                  <td>{float(row.get('単勝オッズ',0)):.1f}</td>
                  <td>{float(row.get('勝率(AI予測)',0))*100:.1f}%</td>
                  <td>{float(row.get('複勝率(AI予測)',0))*100:.1f}%</td>
                  <td style="{ev_color}">{ev_val:.2f}</td>
                </tr>"""
                if rank < 5 and ev_val >= ev_threshold:
                    ev_summary.append({'レース': f"{r['place']}{r['num']}R", '印': row.get('印',''), '馬名': row.get('馬名',''), 'EV': ev_val})
            races_html += f"""
            <div class="race-block">
              <h3>■ {r['place']} {r['num']}R ({r['track']}{r['dist']}m)</h3>
              <p class="conf">{r.get('confidence','')[:60]}</p>
              <p class="pace">展開: {r.get('pace','')[:80]}</p>
              <table>
                <thead><tr><th>印</th><th>馬番</th><th>馬名</th><th>脚質</th><th>オッズ</th><th>勝率</th><th>複勝率</th><th>EV</th></tr></thead>
                <tbody>{rows_html}</tbody>
              </table>
              <p class="reco">推奨: {r.get('reco','')[:100]}</p>
            </div>"""
        
        ev_html = ""
        if ev_summary:
            ev_rows = "".join(f"<tr><td>{r['印']}</td><td>{r['レース']}</td><td>{r['馬名']}</td><td style='color:#cc0000;font-weight:bold'>{r['EV']:.2f}</td></tr>"
                             for r in sorted(ev_summary, key=lambda x: x['EV'], reverse=True))
            ev_html = f"""<div class="ev-summary">
              <h3>💰 本日の注目馬 (EV{ev_threshold}以上・上位5頭内)</h3>
              <table><thead><tr><th>印</th><th>レース</th><th>馬名</th><th>EV</th></tr></thead>
              <tbody>{ev_rows}</tbody></table></div>"""
        
        date_str = results_list[0]['date'] if results_list else ''
        html = f"""<!DOCTYPE html>
<html lang="ja"><head><meta charset="UTF-8">
<title>keiba-ebye 予想レポート {date_str}</title>
<style>
  body {{ font-family: 'Hiragino Kaku Gothic ProN','Noto Sans JP','Meiryo',sans-serif; font-size:11px; margin:10px; color:#222; }}
  h1 {{ font-size:16px; border-bottom:2px solid #2c3e7a; padding-bottom:4px; color:#2c3e7a; }}
  h3 {{ font-size:12px; margin:12px 0 4px; color:#2c3e7a; border-left:3px solid #2c3e7a; padding-left:6px; }}
  .race-block {{ margin-bottom:16px; page-break-inside:avoid; }}
  .conf {{ font-size:10px; color:#555; margin:2px 0; }}
  .pace {{ font-size:10px; color:#444; margin:2px 0; }}
  .reco {{ font-size:10px; background:#f0f8ff; padding:4px 6px; border-radius:3px; margin-top:4px; }}
  table {{ border-collapse:collapse; width:100%; margin:4px 0; font-size:10px; }}
  th {{ background:#2c3e7a; color:white; padding:3px 5px; text-align:center; }}
  td {{ border:1px solid #ddd; padding:2px 4px; text-align:center; }}
  tr:nth-child(even) {{ background:#f8f8f8; }}
  .ev-summary {{ margin-top:16px; padding:8px; background:#fff8f0; border:1px solid #ffd0a0; border-radius:4px; }}
  @media print {{ body {{ margin:5mm; }} .race-block {{ page-break-inside:avoid; }} }}
</style></head>
<body>
<h1>🐴 keiba-ebye AI予想レポート — {date_str}</h1>
{races_html}
{ev_html}
<p style="font-size:9px;color:#888;margin-top:20px">Generated by keiba-ebye / ブラウザでCtrl+P→PDFで保存できます</p>
</body></html>"""
        return html.encode('utf-8')
    except Exception as e:
        return None



def generate_txt_report(results_list, ev_threshold=1.5):
    """noteに貼りやすい・読みやすいプレーンテキスト形式のレポートを生成"""
    out = []
    ev_summary = []

    date_str = results_list[0].get("date", "") if results_list else ""
    out.append(f"🏇 keiba-ebye AI予想レポート  {date_str}")
    out.append("keiba-ebye（ebi × AI × Eye）によるAI競馬予想")
    out.append("")

    for r in results_list:
        place = r.get("place", "")
        num   = r.get("num", "")
        track = r.get("track", "")
        dist  = r.get("dist", "")
        conf  = r.get("confidence", "")
        pace  = r.get("pace", "")

        out.append("=" * 44)
        out.append(f"■ {place} {num}R  {track}{dist}m")
        if conf: out.append(conf)
        out.append("=" * 44)

        if pace:
            out.append(f"[展開予想] {pace}")
            out.append("")

        # 予想表（固定幅テキスト）
        out.append(f"{'印':<3} {'馬番':>3} {'馬名':<12} {'脚質':<5} {'オッズ':>7} {'勝率':>6} {'複勝率':>7} {'EV':>5}")
        out.append("-" * 56)
        for rank, row in r["df"].iterrows():
            try:
                imp  = str(row["印"] or "").ljust(2)
                num_ = int(row["馬番"])
                name = str(row["馬名"])[:10]
                stle = str(row.get("脚質カテゴリ", ""))[:4]
                odds = float(row["単勝オッズ"])
                wp   = row["勝率(AI予測)"] * 100
                fp   = row["複勝率(AI予測)"] * 100
                ev   = float(row.get("期待値", 0) or 0)
                ev_str = f"{ev:4.2f}"
                mark = " ★" if ev >= ev_threshold else ""
                out.append(f"{imp:<3} {num_:>3} {name:<12} {stle:<5} {odds:>6.1f}倍 {wp:>5.1f}% {fp:>6.1f}% {ev_str}{mark}")
                if rank < 5 and ev >= ev_threshold:
                    ev_summary.append({"レース": f"{place}{num}R", "印": row["印"],
                                       "馬番": num_, "馬名": row["馬名"],
                                       "EV": ev, "勝率": f"{wp:.1f}%", "オッズ": odds})
            except Exception as _e:
                logger.debug(f'generate_txt_report行処理スキップ: {_e}')
        out.append("-" * 56)
        out.append("★ = 期待値" + str(ev_threshold) + "以上の注目馬")
        out.append("")

        # 注目トピック
        if r.get("topics"):
            out.append("[注目トピック]")
            for t in r["topics"]:
                clean_t = t.replace("**", "")
                out.append(f"  {clean_t}")
            out.append("")

        # 推奨買い目
        reco_raw = r.get("reco", "")
        if "AIの推し理由" in reco_raw:
            reco_raw = reco_raw[:reco_raw.index("AIの推し理由")].strip()
        if reco_raw:
            out.append("[推奨買い目]")
            out.append(f"  {reco_raw.strip()}")
            out.append("")

    # 横断EV注目馬まとめ
    if ev_summary:
        out.append("")
        out.append("=" * 44)
        out.append(f"💰 本日の注目馬（期待値{ev_threshold}以上・印あり）")
        out.append("=" * 44)
        for row in sorted(ev_summary, key=lambda x: x["EV"], reverse=True):
            out.append(f"  {row['印']} {row['レース']} {row['馬番']}番 {row['馬名']}"
                       f"  EV:{row['EV']:.2f}  オッズ:{row['オッズ']}倍  勝率:{row['勝率']}")
        out.append("")

    out.append("=" * 44)
    out.append("keiba-ebye / 予想はAI参考情報です。馬券は自己責任でお願いします。")
    return "\n".join(out)
